// src/lib/default-data.ts
import type { KpiCategory, KboCategory, NotificationTemplate } from "@/types";

export const DEFAULT_KPI_CATEGORIES: KpiCategory[] = [
  {
    id: "default-financial",
    company: "Global",
    code: "F",
    name: "Financial",
    description: "Indikator yang berkaitan dengan kinerja keuangan dan efisiensi biaya.",
    status: "Aktif",
  },
  {
    id: "default-customer",
    company: "Global",
    code: "C",
    name: "Customer & Market",
    description: "Indikator yang mengukur kepuasan pelanggan dan posisi di pasar.",
    status: "Aktif",
  },
  {
    id: "default-internal",
    company: "Global",
    code: "I",
    name: "Internal Business Process",
    description: "Indikator yang berkaitan dengan efisiensi dan kualitas proses bisnis internal.",
    status: "Aktif",
  },
  {
    id: "default-learning",
    company: "Global",
    code: "L",
    name: "Learning & Grow",
    description: "Indikator yang mengukur pengembangan kapabilitas karyawan dan organisasi.",
    status: "Aktif",
  },
];

export const DEFAULT_KBO_CATEGORIES: KboCategory[] = [
  {
    id: "C1",
    company: "Global",
    name: "Core Competency",
    description: "Kompetensi dasar yang mencerminkan nilai dan budaya perusahaan. Wajib dimiliki semua karyawan.",
    status: "Aktif",
  },
  {
    id: "G1",
    company: "Global",
    name: "Generic Competency",
    description: "Kompetensi umum berdasarkan level atau fungsi jabatan. Mendukung efektivitas kerja.",
    status: "Aktif",
  },
  {
    id: "S1",
    company: "Global",
    name: "Specific Competency",
    description: "Kompetensi teknis sesuai bidang atau profesi tertentu. Menunjang kinerja spesifik jabatan.",
    status: "Aktif",
  }
];


export const SYSTEM_EVENTS = [
  {
    module: "Manajemen Kinerja (KPI)",
    events: [
      { id: 'kpi_deadline_reminder', name: 'Pengingat Deadline KPI', description: 'Terkirim H-X hari sebelum tanggal deadline pengisian KPI bulanan. Menargetkan karyawan yang belum menginput data.' },
      { id: 'kpi_submission_event', name: 'Karyawan Menyimpan KPI', description: 'Terkirim saat karyawan menyimpan/memperbarui data pencapaian KPI. Bisa menargetkan atasan atau manajemen.' },
      { id: 'kpi_approval_event', name: 'Laporan KPI Disetujui/Ditolak', description: 'Terkirim saat atasan menyetujui atau menolak laporan KPI bawahan. Menargetkan karyawan yang bersangkutan.' },
    ],
  },
  {
    module: "Penilaian Kompetensi (KBO) & Appraisal",
    events: [
      { id: 'appraisal_cycle_starts', name: 'Siklus Appraisal Dimulai', description: 'Terkirim pada hari pertama periode appraisal dimulai, sesuai "Pengaturan Appraisal".' },
      { id: 'appraisal_cycle_reminder', name: 'Pengingat Akhir Siklus Appraisal', description: 'Terkirim H-X hari sebelum siklus appraisal berakhir untuk mengingatkan peserta yang belum selesai.' },
      { id: 'kbo_assessment_assigned', name: 'Tugas Penilaian KBO Ditugaskan', description: 'Terkirim saat Admin mempublikasikan tugas penilaian KBO dari menu pemetaan.' },
      { id: 'kbo_assessment_completed', name: 'Penilaian KBO Selesai', description: 'Terkirim kepada karyawan (subjek) saat seorang penilai (rater) menyelesaikan penilaian KBO untuknya.' },
    ],
  },
  {
    module: "Pembelajaran (LMS)",
    events: [
      { id: 'lms_new_course_published', name: 'Kursus Baru Diterbitkan', description: 'Terkirim saat Admin mem-publish kursus baru yang relevan dengan target audiens karyawan.' },
      { id: 'lms_activity_deadline_reminder', name: 'Pengingat Deadline Aktivitas LMS', description: 'Terkirim H-X hari sebelum sebuah aktivitas dalam "Program Pembelajaran" berakhir.' },
      { id: 'lms_course_completion', name: 'Karyawan Menyelesaikan Kursus', description: 'Terkirim saat seorang karyawan mencapai 100% progres atau lulus ujian akhir sebuah kursus.' },
    ],
  },
  {
    module: "OKR (Objectives & Key Results)",
    events: [
      { id: 'okr_assigned', name: 'OKR Baru Ditugaskan', description: 'Terkirim kepada seorang karyawan saat ia ditunjuk sebagai penanggung jawab (owner) sebuah OKR baru.' },
      { id: 'okr_progress_reminder', name: 'Pengingat Update Progres OKR', description: 'Dapat dijadwalkan (misal, mingguan) untuk mengingatkan semua owner OKR aktif agar mengupdate progres mereka.' },
    ],
  },
    {
    module: "Administrasi & Lainnya",
    events: [
      { id: 'new_memo_received', name: 'Memo Internal Baru Diterima', description: 'Terkirim seketika saat seorang pengguna menerima pesan memo baru dari pengguna lain.' },
      { id: 'document_shared', name: 'Dokumen Baru Dibagikan', description: 'Terkirim saat Admin membagikan dokumen (misal: kontrak) kepada karyawan tertentu.' },
    ],
  },
];

export const DEFAULT_NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  // --- KPI ---
  {
    id: 'default_kpi_submission',
    isDefault: true,
    company: 'Global',
    name: 'Default: Laporan KPI Dikirim (untuk Atasan)',
    triggerEventId: 'kpi_submission_event',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'supervisor',
    subject: 'Update KPI dari {{nama_subjek}}',
    message: 'Hai {{nama_pengguna}}, anggota tim Anda, {{nama_subjek}}, telah memperbarui laporan KPI mereka untuk periode {{periode}}. Silakan tinjau di halaman laporan tim.',
    status: 'Active',
  },
  {
    id: 'default_kpi_deadline_reminder',
    isDefault: true,
    company: 'Global',
    name: 'Default: Pengingat Deadline KPI',
    triggerEventId: 'kpi_deadline_reminder',
    triggerCondition: 'before_start',
    triggerOffsetDays: 3,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Pengingat: Deadline Pengisian KPI',
    message: 'Halo {{nama_pengguna}}, jangan lupa untuk mengisi pencapaian KPI periode {{periode}}. Batas waktu pengisian adalah 3 hari lagi.',
    status: 'Active',
  },
  {
    id: 'default_kpi_approval_event',
    isDefault: true,
    company: 'Global',
    name: 'Default: Status Persetujuan KPI',
    triggerEventId: 'kpi_approval_event',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Update Persetujuan Laporan KPI',
    message: 'Laporan KPI Anda untuk periode {{periode}} telah ditinjau oleh atasan. Silakan cek aplikasi untuk melihat status persetujuan.',
    status: 'Active',
  },
  // --- Appraisal & KBO ---
  {
    id: 'default_appraisal_cycle_starts',
    isDefault: true,
    company: 'Global',
    name: 'Default: Siklus Penilaian Dimulai',
    triggerEventId: 'appraisal_cycle_starts',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Siklus Penilaian Kinerja Telah Dimulai',
    message: 'Siklus penilaian kinerja untuk periode {{nama_event}} telah resmi dimulai. Silakan periksa Action Center Anda untuk tugas-tugas penilaian yang perlu diselesaikan.',
    status: 'Active',
  },
  {
    id: 'default_appraisal_cycle_reminder',
    isDefault: true,
    company: 'Global',
    name: 'Default: Pengingat Akhir Siklus Appraisal',
    triggerEventId: 'appraisal_cycle_reminder',
    triggerCondition: 'before_start',
    triggerOffsetDays: 3,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Pengingat: Siklus Penilaian Segera Berakhir',
    message: 'Perhatian {{nama_pengguna}}, siklus penilaian kinerja untuk periode {{nama_event}} akan berakhir dalam 3 hari. Mohon selesaikan semua tugas penilaian Anda.',
    status: 'Active',
  },
  {
    id: 'default_kbo_assessment_assigned',
    isDefault: true,
    company: 'Global',
    name: 'Default: Tugas Penilaian KBO Baru',
    triggerEventId: 'kbo_assessment_assigned',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Tugas Penilaian Kompetensi Baru',
    message: 'Halo {{nama_pengguna}}, Anda memiliki tugas baru untuk menilai kompetensi (KBO) dari {{nama_subjek}}. Mohon selesaikan sebelum siklus berakhir.',
    status: 'Active',
  },
   {
    id: 'default_kbo_assessment_completed',
    isDefault: true,
    company: 'Global',
    name: 'Default: Penilaian KBO Diterima',
    triggerEventId: 'kbo_assessment_completed',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Anda Menerima Penilaian Kompetensi Baru',
    message: 'Halo {{nama_pengguna}}, Anda baru saja menerima penilaian kompetensi (KBO) dari salah seorang penilai. Hasil keseluruhan akan tersedia saat siklus penilaian berakhir.',
    status: 'Active',
  },
  // --- LMS ---
  {
    id: 'default_lms_new_course_published',
    isDefault: true,
    company: 'Global',
    name: 'Default: Kursus LMS Baru',
    triggerEventId: 'lms_new_course_published',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Kursus Baru Untuk Anda: {{nama_event}}',
    message: 'Halo {{nama_pengguna}}, ada kursus baru yang sesuai dengan peran Anda: "{{nama_event}}". Ayo mulai belajar di portal LMS!',
    status: 'Active',
  },
  {
    id: 'default_lms_activity_deadline_reminder',
    isDefault: true,
    company: 'Global',
    name: 'Default: Pengingat Deadline LMS',
    triggerEventId: 'lms_activity_deadline_reminder',
    triggerCondition: 'before_start',
    triggerOffsetDays: 2,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Pengingat: Aktivitas LMS Segera Berakhir',
    message: 'Halo {{nama_pengguna}}, jangan lupa selesaikan aktivitas "{{nama_event}}" dalam program pembelajaran Anda. Batas waktu tinggal 2 hari lagi!',
    status: 'Active',
  },
  {
    id: 'default_lms_course_completion',
    isDefault: true,
    company: 'Global',
    name: 'Default: Kursus LMS Selesai',
    triggerEventId: 'lms_course_completion',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Selamat! Anda Telah Menyelesaikan Kursus',
    message: 'Kerja bagus, {{nama_pengguna}}! Anda telah berhasil menyelesaikan kursus "{{nama_event}}". Lihat hasilnya sekarang!',
    status: 'Active',
  },
  // --- OKR ---
  {
    id: 'default_okr_assigned',
    isDefault: true,
    company: 'Global',
    name: 'Default: OKR Baru Ditugaskan',
    triggerEventId: 'okr_assigned',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Anda Ditugaskan sebagai Penanggung Jawab OKR',
    message: 'Hai {{nama_pengguna}}, Anda telah ditunjuk sebagai penanggung jawab (owner) untuk Objective baru: "{{nama_event}}".',
    status: 'Active',
  },
  {
    id: 'default_okr_progress_reminder',
    isDefault: true,
    company: 'Global',
    name: 'Default: Pengingat Update OKR',
    triggerEventId: 'okr_progress_reminder',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Pengingat Mingguan: Update Progres OKR Anda',
    message: 'Halo {{nama_pengguna}}, ini adalah pengingat untuk memperbarui progres semua OKR yang menjadi tanggung jawab Anda minggu ini. Terima kasih!',
    status: 'Active',
  },
  // --- Admin & Lainnya ---
  {
    id: 'default_new_memo_received',
    isDefault: true,
    company: 'Global',
    name: 'Default: Memo Baru Diterima',
    triggerEventId: 'new_memo_received',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Anda Menerima Memo Baru dari {{nama_subjek}}',
    message: 'Anda menerima pesan memo baru dari {{nama_subjek}} dengan subjek: "{{nama_event}}". Silakan cek kotak masuk memo Anda.',
    status: 'Active',
  },
  {
    id: 'default_document_shared',
    isDefault: true,
    company: 'Global',
    name: 'Default: Dokumen Baru Dibagikan',
    triggerEventId: 'document_shared',
    triggerCondition: 'on_start',
    triggerOffsetDays: 0,
    channel: 'app',
    recipientTarget: 'subject',
    subject: 'Dokumen Baru untuk Anda: {{nama_event}}',
    message: 'Halo {{nama_pengguna}}, sebuah dokumen baru berjudul "{{nama_event}}" telah dibagikan dengan Anda. Silakan cek pusat dokumen.',
    status: 'Active',
  },
];
